"""Third migration

Revision ID: 2e65a42b37e6
Revises: 69e1ecd50eac
Create Date: 2022-07-23 02:24:10.278529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e65a42b37e6'
down_revision = '69e1ecd50eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('height', sa.Integer(), nullable=False))
    op.drop_column('profile', 'school')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('school', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('profile', 'height')
    # ### end Alembic commands ###
