"""Third migration

Revision ID: 32a4cf929487
Revises: b72e2f7f42b4
Create Date: 2022-07-23 02:50:53.289077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a4cf929487'
down_revision = 'b72e2f7f42b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('sex', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'sex')
    # ### end Alembic commands ###
