"""Third migration

Revision ID: b72e2f7f42b4
Revises: 21f42920b92f
Create Date: 2022-07-23 02:50:36.118521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72e2f7f42b4'
down_revision = '21f42920b92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('school', sa.String(length=20), nullable=False))
    op.drop_column('profile', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('sex', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('profile', 'school')
    # ### end Alembic commands ###
