"""Third migration

Revision ID: dfdd22366e2c
Revises: 2e65a42b37e6
Create Date: 2022-07-23 02:26:57.838171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdd22366e2c'
down_revision = '2e65a42b37e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('school', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'school')
    # ### end Alembic commands ###
